Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-11"
    config.vm.provider "virtualbox" do |vb|
        #   # Display the VirtualBox GUI when booting the machine
        #   vb.gui = true
        #
        #   # Customize the amount of memory on the VM:
          vb.memory = "4096"
          vb.gui = true
          vb.cpus = 1
        end
  end